input {
    stdin {
    }
    jdbc {
      # 配置数据库信息
      jdbc_connection_string => "jdbc:mysql://192.168.3.210:3306/literature_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
      jdbc_user => "logstash_remote"
      jdbc_password => "1234"
      
      # mysql驱动所在位置
      jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
      jdbc_driver_library => "/usr/share/logstash/mysql-connector-j-9.7.0.jar"

      jdbc_paging_enabled => "true"
      jdbc_page_size => "50000"
      jdbc_default_timezone => "Asia/Shanghai"
      #sql执行语句
	  statement => "SELECT * FROM literature_metadata"
      # 定时字段 各字段含义（由左至右）分、时、天、月、年，全部为*默认含义为每分钟都更新
      schedule => "* * * * *"
      # 是否将 sql 中 column 名称转小写
      lowercase_column_names => false
    }
}
output {
    elasticsearch {
        hosts => ["${ES_DOCKER_HOST}"]
        index => "literature_metadata"
        # 文档id，%{id}意思是取mysql查询出来的id的值，并将其映射到ES的_id字段中
        document_id => "%{id}"
        user => "${LOGSTASH_ELASTICSEARCH_USERNAME}"
        password => "${LOGSTASH_ELASTICSEARCH_PASSWORD}"
        # action => "%{[@metadata][action]}"
        # doc_as_upsert => true
    }
    stdout {
        codec => json_lines
    }
}
